
<!-- Header -->
<header>
    <div class="search-block">
        <?php echo $this->getChildHtml('topSearch') ?>
        <div class="blank-cell"></div>
    </div>
    <div class="main-bar">
        <a href="" class="cart-button"><img src="<?php echo $this->getSkinUrl('images/header/cart_01.svg') ?>" alt="Cart"></a>
        <a href="/" class="logo mobile"><img src="<?php echo $this->getSkinUrl('images/header/iqm_logo_full.svg') ?>" alt="Home"></a>
        <div class="menu-button" id="menuButton">Menu</div>


        <div class="nav-box">
            <a href="/" class="logo"><img src="<?php echo $this->getSkinUrl('images/header/iqm_logo_full.svg') ?>" alt="Home"></a>
            <?php echo $this->getChildHtml('topMenu') ?>
            <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/user_links.phtml')->toHtml() ?>
        </div>

        <div class="nav-box" id="mobileNav">
            <?php echo $this->getChildHtml('topMenu') ?>
            <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/user_links.phtml')->toHtml() ?>
        </div>

    </div>
</header>
<!-- /Header -->
