<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!-- 1column -->
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
        <?php echo $this->getChildHtml('header') ?>
        <section class="content-block">
                     <!-- Mobile nav -->
<!--
                    <ul class="main-nav">
                <div class="nav-box" id="mobileNav">
                        <li><a href="">Magento Development</a></li>
                        <li><a href="">Magento Extentions</a></li>
                        <li><a href="">E-commerce Designs</a></li>
                        <li><a href="">Contact</a></li>
                    </ul>
                    <?php echo $this->getChildHtml('topNav') ?>

                    <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/user_links.phtml')->toHtml() ?>

                </div>
-->
             <!-- /Mobile nav -->
                <?php echo $this->getChildHtml('breadcrumbs') ?>
                <div class="col-main">
                    <?php echo $this->getChildHtml('global_messages') ?>
                    <?php echo $this->getChildHtml('content') ?>
                </div>
        </section>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
